# transformação IMU (x´,y´,z´) → referencial local do robô (x,y,z)



In [1]:

import numpy as np

# Parâmetros de calibração no notebook calibracao_imu.ipynb (res2.x)
SCALE = 0.000598
VIES = np.array([-109.79370126, -104.46455324, -253.01762059])
GANHOS = np.array([0.99708971, 0.99872567, 0.99779582])

In [2]:

path = "/home/mateus/poli_26/elem_robotica/robotica_movel/aula5"
g1 = np.load(path+"/dados_imu_teste_normalizados_1.npy")
g2 = np.load(path+"/dados_imu_teste_normalizados_2.npy")
g3 = np.load(path+"/dados_imu_teste_normalizados_3.npy")
g4 = np.load(path+"/dados_imu_teste_normalizados_4.npy")

g1 = g1.mean(axis=0)
g2 = g2.mean(axis=0)
g3 = g3.mean(axis=0)    
g4 = g4.mean(axis=0)

g = np.mean([g1, g2, g3, g4], axis=0)

In [3]:
print(g1) #gravity measured upwards

[-0.12550811 -0.02397149  0.99180239]


### eixo z em função de x´, y´, z´

In [4]:
print(g)
k = -g/np.linalg.norm(g)    # z axis of the robot (points downwards according to convention)
print(k)


[-0.12088443 -0.02783838  0.99221944]
[ 0.12089123  0.02783995 -0.99227529]


### eixo y em função de x´, y´, z´

In [5]:


g5 = np.load(path+"/dados_imu_teste_normalizados_inclinado.npy")
g5 = g5.mean(axis=0)
d = g4 - g5

In [6]:
# j = produto vetorial g5 x (d = g4 - g5)
j = np.cross(d, k)
j = j / np.linalg.norm(j)
print(j)

[ 0.00416124 -0.99961207 -0.02753882]


### eixo x em função de x´ ,y´ ,z´

In [7]:
i = np.cross(j, k)
i = i / np.linalg.norm(i)
print(i)

[9.92657038e-01 7.99896213e-04 1.20960183e-01]


### matrizes R_{imu}^{robô}

In [8]:
#IMU orientada como robô - x frente, y direita e z baixo
Q_FDB = np.array([i.T, 
                  j.T, 
                  k.T])
print("Q (Frente-Direita-Baixo):")
print(Q_FDB)    
np.save(path+"/Q_FDB.npy", Q_FDB)


Q (Frente-Direita-Baixo):
[[ 9.92657038e-01  7.99896213e-04  1.20960183e-01]
 [ 4.16124223e-03 -9.99612074e-01 -2.75388179e-02]
 [ 1.20891232e-01  2.78399461e-02 -9.92275288e-01]]


In [9]:
Q_FEC = np.array([i.T,
                  -j.T,
                  -k.T])
print("Q (Frente-Esquerda-Cima):")
print(Q_FEC)
np.save(path+"/Q_FEC.npy", Q_FEC)

Q (Frente-Esquerda-Cima):
[[ 9.92657038e-01  7.99896213e-04  1.20960183e-01]
 [-4.16124223e-03  9.99612074e-01  2.75388179e-02]
 [-1.20891232e-01 -2.78399461e-02  9.92275288e-01]]
